### ISSUE TITLE
About page content

### ISSUE THREAD

**Issue by padr31** [hackkosice/new-web#1]
Fill in the content of the about page:
- Make page resemble our current HK page
- Add images of people (make sure images are minified for web size, i.e. no more than 50kb each)
- Remove sponsors part
- Add a tutorial to notion on how to add someone's profile to the about page (https://www.notion.so/hackkosice/Tutorials-b1a77b110d304a28a0f775f8dc6840d6)

**Comment by jjurm** [comment]
I finished the page (8d4b33e7): https://fire.hackkosice.com/about/
