### ISSUE TITLE
Set up Firebase to compress served files (gzip)

### ISSUE THREAD

**Issue by jjurm** [hackkosice/new-web#12]
The rules defined in the [.htaccess](https://github.com/hackkosice/new-web/blob/master/themes/orbitor-hugo/static/.htaccess) file are likely not used by Firebase

**Comment by hruskraj** [comment]
I think Firebase [is already serving compressed data](https://stackoverflow.com/questions/34318491/serving-gzipped-files-on-firebase-hosting). By comparing
`curl -s -v -H "Accept-Encoding: gzip" https://fire.hackkosice.com 1> /dev/null`
and
`curl -s -v https://fire.hackkosice.com 1> /dev/null`,
one can see a difference in content length.

**Comment by jjurm** [comment]
Thank you!
