### ISSUE TITLE
Fix navigation bar in narrow screens

### ISSUE THREAD

**Issue by jjurm** [hackkosice/new-web#20]
The logo is too small (I use vertical display, i.e. 1080px wide - not too uncommon)

![image](https://user-images.githubusercontent.com/6285777/87261449-8ef90d80-c4b6-11ea-8f1c-492347dfb64e.png)

**Comment by padr31** [comment]
Resolved. Also made the text nowrap. 
![image](https://user-images.githubusercontent.com/6302691/88225988-afba2380-cc6b-11ea-87e0-ef419c6fd7f8.png)
