### ISSUE TITLE
Sponsors Page: Onboarding for Platinum, Gold, Silver and Bronze respectively

### ISSUE THREAD

**Issue by pridilla** [hackkosice/new-web#31]
I am currently working on sponsors onboarding page based on https://hackkosice.com/sponsors/ but I miss collapsable panels at the bottom of the page. Moreover, I would really appreciate having links for packages (hackkosice.com/platinum etc.) also on the new webpage, where the content of the page (more precisely these panels for sponsor packages) would be filtered based on that link.

**Comment by jjurm** [comment]
I added shortcode for including files (90f19d8c69901819687fd32e251c80d34aa0999a), see https://fire.hackkosice.com/examples/simple-sections/

What collapsible panels do you need? This currently has collapsible sections: https://fire.hackkosice.com/sponsors/
Do you need to customise styles?

**Comment by pridilla** [comment]
If you check pages hackkosice.com/sponsors and hackkosice.com/platinum per se, you will immediately spot the difference in comparison with dev version at the bottom.

**Comment by jjurm** [comment]
I added styling of the `details` blocks, see 479ee5b2ebde130bf0f351a53bcefff6add03c84

**Comment by jjurm** [comment]
@pridilla can this be considered resolved? If so, can you finish #14 as well?

**Comment by jjurm** [comment]
Done.
